//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int order_id { get; set; }
        public string order_image { get; set; }
        public System.DateTime order_date { get; set; }
        public int order_quantity { get; set; }
        public decimal order_total { get; set; }
        public int customer_id { get; set; }
        public int shoe_id { get; set; }
    
        public virtual Registration Registration { get; set; }
        public virtual Product Product { get; set; }
    }
}
